### ISSUE TITLE
camera's perspective error

### ISSUE THREAD

**Issue by zhongjiejiang** [Arne-Petersen/Plenoptic-Simulation#1]
Hi 

I use this plugin in the blender 2.80 version, but I can't get the right camera's perspective in second 3D view, 

![WechatIMG59_1](https://user-images.githubusercontent.com/1235650/72334426-3fe54200-36f8-11ea-9063-0b5347e91536.jpg)

I can't get the Checkerboard image in  camera's perspective, how can I get the right Checkerboard image, thanks.

json

**Comment by Ungetym** [comment]
You have to change the viewport shading to "Rendered". The buttons for the viewport shading are marked in blue in this image:
https://raw.githubusercontent.com/Arne-Petersen/Plenoptic-Simulation/master/images/1.jpg

In order to see these buttons, you can drag the views options using the middle mouse button, e.g. click the middle mouse button on the dropdown menu currently showing "Global" and drag the whole bar to the left.

**Comment by zhongjiejiang** [comment]
I have changed the viewport shading to "Rendered"
![data](https://user-images.githubusercontent.com/1235650/72400556-9d26d500-3784-11ea-9e23-1d3ddb4df5ac.jpg)


thanks
json

**Comment by Ungetym** [comment]
Could you save this to a .blend file and upload it for me to have a look at?
Thanks,
Tim

**Comment by PAKFA** [comment]
Hi, I also encounter the same problem. This is my .blend file.

[notexture.blend.zip](https://github.com/Arne-Petersen/Plenoptic-Simulation/files/6302414/notexture.blend.zip)

Could you please help me checking the file?
Thank you very much!

**Comment by Ungetym** [comment]
I checked your file with Blender 2.91 and was able to fix the problem by setting the correct render engine. Go to "Render properties" (2nd vertical tab on the right) and select "Cycles" as render engine.

Best regards,
Tim

**Comment by Ungetym** [comment]
Note: I'll leave this issue open as "todo" until we have implemented the automated selection of the correct render engine upon the creation of a new camera.

**Comment by Ungetym** [comment]
Should be fixed with the latest commit.

**Comment by PAKFA** [comment]
> I checked your file with Blender 2.91 and was able to fix the problem by setting the correct render engine. Go to "Render properties" (2nd vertical tab on the right) and select "Cycles" as render engine.
> 
> Best regards,
> Tim

This works! Thank you!
