### ISSUE TITLE
Example File for Figure 5

### ISSUE THREAD

**Issue by corner100** [Arne-Petersen/Plenoptic-Simulation#11]
Hello,

is it possible to get an example blend file for figure 5. Or a detailed instruction on how to set up the system to get that kind of image.
I am not able to reproduce the images from figure 5 with the instructions in the current reamdme.

Best regards

**Comment by PAKFA** [comment]
Please see the closed issue,
https://github.com/Arne-Petersen/Plenoptic-Simulation/issues/1

**Comment by Ungetym** [comment]
I created a test file with Blender 2.91.2 for you (so please use this or a later version to avoid incompatibilities):
https://cloud.rz.uni-kiel.de/index.php/s/skpwjjsLMLDnLPP

After loading this file, you have to set the "Viewport Shading" of the upper left view to "Rendered" (see e.g. [here](https://blender.stackexchange.com/questions/180413/where-is-the-viewport-shading-in-blender-2-8)).

As PAKFA is suggesting, your configuration might only be missing the correct render engine setting. This must be set to Cycles (which was done for the example above).

Best regards,
Tim

**Comment by corner100** [comment]
Hi Tim,

is it possible to upload the blend file to create figure 5 plenoptic 1.0 again? The link is not working anymore.

best regards
corner100
