### ISSUE TITLE
Dark rendering

### ISSUE THREAD

**Issue by AnnahAdams** [Arne-Petersen/Plenoptic-Simulation#17]
I have been trying to follow the steps in the file. However, the camera view is pitch black. I have even tried different parameters but no luck. Any solution to this problem? Also is there a way to choose square MLA than the hexagonal ones?

**Comment by Ungetym** [comment]
Sorry for the late answer, I just found the unanswered issues here. :/

Regarding the problem: I am not sure, whether this is still an issue, but I had reports from some users, that the current add-on version might only work with Blender versions >=3.0. 

However, note that in a few weeks I will release the next version of this add-on featuring 100s of realistic main lenses and some other nice features such as refocusing by moving lens groups. Keep an eye on this repo's readme!

**Comment by Ungetym** [comment]
The new version should fix several problems: [https://gitlab.com/ungetym/blender-camera-generator](https://gitlab.com/ungetym/blender-camera-generator)
