### ISSUE TITLE
Blender report the error “Traceback(most recent call last)” when activate Generic: Camera_Generator addons

### ISSUE THREAD

**Issue by Kamijio-Misaka** [Arne-Petersen/Plenoptic-Simulation#18]
Dear Arne and Tim,

Blender report the error “Traceback(most recent call last)” when I try to activate Generic: Camera_Generator addons. At first, I thought it was a version problem. Then I tried the Blender version of 3.3, 2.93, and 2.83, and the results failed the same as.
it reported this.
`Traceback (most recent call last):
  File "C:\Users\11091\Desktop\Challenge Cup\blender-2.93.14-windows-x64\blender-2.93.14-windows-x64\2.93\scripts\modules\addon_utils.py", line 386, in enable
    mod.register()
  File "C:\Users\11091\Desktop\Challenge Cup\blender-2.93.14-windows-x64\blender-2.93.14-windows-x64\2.93\scripts\addons\Blender_CamGen\__init__.py", line 33, in register
    data.init()
  File "C:\Users\11091\Desktop\Challenge Cup\blender-2.93.14-windows-x64\blender-2.93.14-windows-x64\2.93\scripts\addons\Blender_CamGen\data.py", line 70, in init
    sellmeier_data = read_dispersion_data(addon_directory+'sellmeier_materials.csv')
  File "C:\Users\11091\Desktop\Challenge Cup\blender-2.93.14-windows-x64\blender-2.93.14-windows-x64\2.93\scripts\addons\Blender_CamGen\io.py", line 171, in read_dispersion_data
    with open(dispersion_file, newline='') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\11091\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts/addons/Blender_CamGen/sellmeier_materials.csv'
`
And this is the picture 
![S4{FG20{BRINA%VY8D_(JT6](https://user-images.githubusercontent.com/80609919/218715533-7731184f-d0f4-478d-a599-093c68c6cbc7.png)

Can I get some suggestions about this error？Thank you very very very  much！！！

**Comment by Ungetym** [comment]
I am afraid [this](https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f) is a problem based on the different path formatting styles in Linux and Windows. Check this. The add-on was developed on Linux and we didn't pay attention to the path formatting and simply hard-coded paths when needed. A fix for this problem would require checking the whole code base and rewriting every path related code fragment. Unfortunately, I currently don't have the time to do this.

BUT: In a few weeks I will release the next version of this add-on featuring 100s of realistic main lenses and some other nice features such as refocusing by moving lens groups. In this new version I will use pathlib to prevent any path formatting trouble. :)

Alternatively, feel free to create a pull-request on the current version if you find the time to fix the problem!

**Comment by jackpt7186** [comment]
Hi, it might be late but I also had this problem.
My solution in windows platform is to copy Blender_CamGen folder to desired location:  C:\Users\"YourUserName"\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons

**Comment by Ungetym** [comment]
The path formatting problem should now be fixed in the new version of the add-on available here: [https://gitlab.com/ungetym/blender-camera-generator](https://gitlab.com/ungetym/blender-camera-generator)

**Comment by jackpt7186** [comment]
Thank you, Tim.
Great work!
