### ISSUE TITLE
"No such file or directory" error on Windows

### ISSUE THREAD

**Issue by tswallen** [Arne-Petersen/Plenoptic-Simulation#2]
When installing the plugin on Windows it could not resolve the CSV files from the paths provided. I will raise a PR hopefully soon.

**Comment by Ungetym** [comment]
That would be very helpful since I currently don't have a Windows machine available. However, you could try to execute Blender as admin to make sure it is not a right management related problem.

Best regards,
Tim

**Comment by tswallen** [comment]
All good. I found the source of the issue...

`bpy.utils.user_resource('SCRIPTS', "addons")` refers to a location in AppData (I'd used the wrong folder). Rookie error on my part - I'll propose and entry in the read me
